CREATE TABLE public.ML (
    id serial PRIMARY KEY,
    escenario integer NOT NULL,
    escenario_description text,
    juego integer NOT NULL,
    juego_nombre text,
    nivel integer NOT NULL,
    nivel_nombre text,
    tiempo_juego integer,
    n_wrong_prom integer,
    n_right_prom integer,
    num_try_prom integer,
    intentos_ok integer,
    correctas_ok integer,
    incorrectas_ok integer,
    tiempo_juego_ok integer,
    eficiencia_valoracion integer,
    eficiencia_conclusion text,
    efectividad_valoracion integer,
    efectividad_conclusion text,
    flexibilidad_valoracion integer,
    flexibilidad_conclusion text,
    satisfaccion_valoracion integer,
    satisfaccion_conclusion text,
    jugabilidad_valoracion integer,
    jugabilidad_conclusion text
);